name: Build & Deploy Backend to Cloud Run

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"
      - ".github/workflows/deploy-backend.yml"
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.CLOUD_RUN_REGION }}
  SERVICE: ${{ secrets.CLOUD_RUN_SERVICE }}
  GAR_LOCATION: ${{ secrets.GAR_LOCATION }}         # e.g. australia-southeast1
  GAR_REPO: ${{ secrets.GAR_REPO }}                 # e.g. installer-repo
  IMAGE: ${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REPO }}/${{ secrets.CLOUD_RUN_SERVICE }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: gh-actions-deployer@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker $GAR_LOCATION-docker.pkg.dev --quiet

      # Helpful debug so we can see the files on the runner
      - name: List backend contents
        run: |
          pwd
          ls -la
          echo "----- backend/ -----"
          ls -la backend
          echo "----- Dockerfile -----"
          sed -n '1,120p' backend/Dockerfile

      - name: Compute short SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build image (classic docker)
        run: |
          docker build \
            -f backend/Dockerfile \
            -t "${IMAGE}:${{ steps.vars.outputs.SHORT_SHA }}" \
            backend
          docker tag "${IMAGE}:${{ steps.vars.outputs.SHORT_SHA }}" "${IMAGE}:latest"

      - name: Push image
        run: |
          docker push "${IMAGE}:${{ steps.vars.outputs.SHORT_SHA }}"
          docker push "${IMAGE}:latest"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy "$SERVICE" \
            --image="${IMAGE}:${{ steps.vars.outputs.SHORT_SHA }}" \
            --region="$REGION" \
            --platform=managed \
            --port=8080 \
            --quiet
