name: Build & Deploy Backend to Cloud Run

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"
      - ".github/workflows/deploy-backend.yml"
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.CLOUD_RUN_REGION }}
  SERVICE: ${{ secrets.CLOUD_RUN_SERVICE }}
  GAR_LOCATION: ${{ secrets.GAR_LOCATION }}
  GAR_REPO: ${{ secrets.GAR_REPO }}
  IMAGE: ${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REPO }}/${{ secrets.CLOUD_RUN_SERVICE }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: gh-actions-deployer@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker $GAR_LOCATION-docker.pkg.dev --quiet

      # --- Debug helpers (safe to keep) ---
      - name: Show backend dir contents
        run: |
          echo "PWD=$(pwd)"
          ls -la
          echo "--- backend ---"
          ls -la backend

      - name: Show Docker version + buildx
        run: |
          docker version
          docker buildx version || true
      # ------------------------------------

            - name: Build image (force classic docker)
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          # Switch Docker to classic builder instead of buildx
          docker buildx use default || true
          docker build \
            -f backend/Dockerfile \
            -t "$IMAGE:$SHORT_SHA" \
            backend
          docker tag "$IMAGE:$SHORT_SHA" "$IMAGE:latest"


      - name: Push image
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          docker push "$IMAGE:$SHORT_SHA"
          docker push "$IMAGE:latest"

      - name: Deploy to Cloud Run
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          gcloud run deploy "$SERVICE" \
            --image="$IMAGE:$SHORT_SHA" \
            --region="$REGION" \
            --platform=managed \
            --port=8080 \
            --quiet
