name: Build & Deploy Backend to Cloud Run

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"
      - ".github/workflows/deploy-backend.yml"
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.CLOUD_RUN_REGION }}
  SERVICE: ${{ secrets.CLOUD_RUN_SERVICE }}
  GAR_LOCATION: ${{ secrets.GAR_LOCATION }}             # e.g. australia-southeast1
  GAR_REPO: ${{ secrets.GAR_REPO }}                    # e.g. installer-repo
  IMAGE: ${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REPO }}/${{ secrets.CLOUD_RUN_SERVICE }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: gh-actions-deployer@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker "${{ env.GAR_LOCATION }}-docker.pkg.dev" --quiet

      - name: List backend contents (debug)
        run: ls -la backend

      - name: Compute short SHA
        id: sha
        run: echo "SHORT=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

            - name: Build image (classic docker)
        working-directory: backend
        run: |
          # Normalize IMAGE to strip any accidental newlines/carriage returns from secrets
          IMAGE_REF="$(printf '%s' "${IMAGE}" | tr -d '\r' | tr -d '\n')"
          echo "Using IMAGE_REF=${IMAGE_REF}"  # will be partially masked by GitHub

          docker build \
            -t "${IMAGE_REF}:${{ steps.sha.outputs.SHORT }}" \
            -t "${IMAGE_REF}:latest" \
            .

      - name: Push image
        run: |
          IMAGE_REF="$(printf '%s' "${IMAGE}" | tr -d '\r' | tr -d '\n')"
          docker push "${IMAGE_REF}:${{ steps.sha.outputs.SHORT }}"
          docker push "${IMAGE_REF}:latest"


      # Force the default Cloud Run endpoint so any inherited override is ignored
      - name: Deploy to Cloud Run
        env:
          CLOUDSDK_API_ENDPOINT_OVERRIDES_RUN: "https://run.googleapis.com/"
        run: |
          gcloud run deploy "${SERVICE}" \
            --image="${IMAGE}:${{ steps.sha.outputs.SHORT }}" \
            --region="${REGION}" \
            --platform=managed \
            --port=8080 \
            --quiet
